### ISSUE TITLE
Problem posting to lab notebook website & correct url

### ISSUE THREAD

**Issue by laurahspencer** [laurahspencer/LabNotebook#1]
I have my lab notebook up and running as a GitHub repository/[page](https://laurahspencer.github.io/LabNotebook/), but when I created a new file under my /posts directory using the same front matter format (pasted below) the post doesn't show up on the webpage. Any suggestions?  

I'm also a bit confused about the fact that my site's url ends with /Notebook; I've read in Barry Clark's [tutorial](https://www.smashingmagazine.com/2014/08/build-blog-jekyll-github-pages/) that this issue arises when you create a url under a project, and thus the subdirectory, but I don't believe this is the issue since the page's source is the masterbranch. Perhaps it's due to the various locations where I can name my Notebook's url: 1) in the _config.yml file & 2) in the Settings tab under "repository name"?

Thanks! 

**Front Matter:**

```

---
layout: post  
title: Does this thing work?

---
```

@sr320 @kubu4 @hputnam @Ellior2 @yaaminiv

**Comment by laurahspencer** [comment]
Problem #1 solved -> the new post file didn't have an .md extension. 

Problem #2 still stands!

**Comment by yaaminiv** [comment]
i found that 1) changing the URL in the settings and 2) changing the URL at the top of the code page did the trick!

**Comment by sr320** [comment]
My impression is that it is /Notebook, because that is the name of your repository..
similar to 
https://hputnam.github.io/Putnam_Lab_Notebook/

**Comment by laurahspencer** [comment]
Got it; it looks like if I wanted my notebook's url to be the simple "username.github.io" I would need to change the name of my notebook's repository to that, as Yaamini has done.  

Thanks ya'll!
