### ISSUE TITLE
Adding comments option to lab notebook

### ISSUE THREAD

**Issue by laurahspencer** [laurahspencer/LabNotebook#4]
@sr320 how can I add the comments section to my lab notebook posts? Is it via Disquis? I've cross checked your lab notebook files with mine and have yet to find the code.

**Comment by sr320** [comment]
See
https://github.com/barryclark/jekyll-now/wiki/How-to-add-Disqus-to-your-blog

**Comment by laurahspencer** [comment]
Got it. Thanks!
